import js from '@eslint/js';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/** Shared flat ESLint config for all RBP workspaces. */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/dev-dist/**',
      '**/node_modules/**',
      '**/public/mockServiceWorker.js',
      // Generated by Playwright.
      '**/e2e/report/**',
      '**/e2e/results/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strict,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
    },
  },
  {
    // shadcn convention: component files also export variants/helpers. Not an HMR concern in a library.
    files: ['packages/ui/**/*.tsx'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  {
    // Mock API boundary: app code talks to /api/v1 via @rbp/api-client and never knows
    // whether MSW or NestJS answered. Only bootstrap, tests and the mock-only dev tools may reach in.
    files: ['apps/web/src/**/*.{ts,tsx}'],
    ignores: [
      'apps/web/src/mocks/**',
      'apps/web/src/main.tsx',
      'apps/web/src/test/**',
      'apps/web/src/**/*.test.{ts,tsx}',
      'apps/web/src/features/dev-tools/**',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/mocks', '@/mocks/*', '**/mocks/*'],
              message:
                'UI code must not depend on the mock API. Use @rbp/api-client via feature query hooks.',
            },
          ],
        },
      ],
    },
  },
  {
    // Fixtures and tests may assert known-present records.
    files: ['**/*.test.{ts,tsx}', '**/mocks/**/*.ts', '**/test/**/*.ts'],
    rules: { '@typescript-eslint/no-non-null-assertion': 'off' },
  },
  {
    // Playwright requires object destructuring for fixtures, even when empty: `({}, testInfo)`.
    files: ['**/e2e/**/*.ts'],
    rules: { '@typescript-eslint/no-non-null-assertion': 'off', 'no-empty-pattern': 'off' },
  },
  {
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: { globals: { ...globals.node } },
  },
);
